[package]
name = "web"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[workspace]

[dependencies]
wasm-bindgen = "0.2.38"

[dependencies.smol]
path = ".."

[dependencies.web-sys]
version = "0.3.15"
features = ["console"]
